config/routes.rb
Rails.application.routes.draw do
  resources :playlist
  root 'playlist#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.save
    redirect_to @playlist
  end
     
  def show
    @playlist = Playlist.find(params[:id])
  end

  def index
    @playlists = Playlist.all
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
   
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render 'edit'
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
   
    redirect_to playlist_index_path
  end

  private
    
  def playlist_params
    params.require(:playlist).permit(:title, :song_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaylistProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlist/edit.html.erb
<h1>Edit Article</h1>
 
<%= form_with(model: @playlist, local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :song_link %><br>
    <%= form.text_area :song_link %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', playlist_index_path %>

app/views/playlist/index.html.erb
<h1>Listing Playlist</h1>
<%= link_to 'New playlist entity', new_playlist_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Options</th>
    <th colspan="3"></th>
  </tr>
 
  <% @playlists.each do |entity| %>
    <tr>
      <td><%= entity.title %></td>
      <td><%= link_to 'Show', playlist_path(entity) %></td>
      <td><%= link_to 'Edit', edit_playlist_path(entity) %></td>
      <td><%= link_to 'Destroy', playlist_path(entity),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/playlist/new.html.erb
<%= form_with scope: :playlist, url: playlist_index_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :song_link %><br>
    <%= form.text_area :song_link %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', playlist_index_path %>

app/views/playlist/show.html.erb
 <p>
  <strong>Title:</strong>
  <%= @playlist.title %>
</p>
 
<p>
  <strong>Song Link:</strong>
  <a href="<%= @playlist.song_link %>"><%= @playlist.song_link %></a>
</p>

<%= link_to 'Back', playlist_index_path %>